### ISSUE TITLE
"onFooterInfiniting"  不是每次都触发

### ISSUE THREAD

**Issue by buddydc** [woowalker/react-native-ptr-control#1]
使用了FlatList,列表的每一项高度不同，上拉刷新的时候有时候可以触发，有时候不能触发

**Comment by woowalker** [comment]
@buddydc 有具体操作吗？建议在真机上调试

**Comment by woowalker** [comment]
@buddydc 有具体点的操作吗？应该是在安卓上吧？建议在真机上调试（能够开启dev为true最好），把log关闭，因为这个库是纯js写的，不可避免有性能问题，对手势的捕捉如果是在dev false的情况下，会显得很卡顿的
