### ISSUE TITLE
使用FlatList时快速滑动到顶部会出现HeaderRefresh

### ISSUE THREAD

**Issue by abbenyyyyyy** [woowalker/react-native-ptr-control#10]
请问有方法可以避免从底部快速滑动到顶部的时候HeaderRefresh出现么？谢谢。

**Comment by woowalker** [comment]
@abbenyyyyyy  应该是安卓机器上是吧？目前应该暂时是没有哈，因为安卓部分刷新头是隐藏在 ScrollView 之中的，我最近对RN的关注有些下降了，不知道现在有没有更好的原生层面的下拉刷新组件，有的话，希望共享一下哈，谢谢。
