### ISSUE TITLE
安卓上首次进入页面会默认刷新

### ISSUE THREAD

**Issue by wenkangzhou** [woowalker/react-native-ptr-control#2]
是否有开关可以控制不开启默认刷新行为，IOS上无此行为，两边的交互就不是很统一。

**Comment by woowalker** [comment]
因为目前js上的手势在安卓上非常容易被scrollView组件剥夺（也就是说，如果在scrollView外面套一层View，然后使用RN管理手势捕获的API，这个手势基本会被scrollView剥夺，从而无法正常管理手势），所以这个刷新头其实是写在scrollView里面的，它占用了scrollView的一些内容空间，自动刷新是因为这部分内容本身在scrollView内部，组件挂载完毕就能看到，当刷新完毕，通过scrollTo将刷新头隐藏起来。

如果要把这个关闭，那就需要在组件刚刚挂载上的时候（componentDidMount）将其scrollTo隐藏起来，当然这是个做法，但有可能会出现刷新头一闪而过的现象，我觉得这样不好。

我尝试过很多种做法，比如下拉的时候再把刷新头添加进去，或者将刷新头进行位移处理，但是都会因为无法正常的获取并判断当前手势而出现或多或少的问题，当前方案我觉得是一个最佳实践。

**Comment by wenkangzhou** [comment]
好的，多谢！

**Comment by renjinlong** [comment]
componentDidMount）将其scrollTo隐藏起来 会导致上拉功能失效不能上拉加载怎么办呢？
