### ISSUE TITLE
How to customize messages?

### ISSUE THREAD

**Issue by fweffort** [woowalker/react-native-ptr-control#3]
Hi,
the messages are in chinese, is there any way to customize this?

**Comment by woowalker** [comment]
@fweffort if you mean the messages is those **chinese annotation**, i am afraid that it is hard to change all chinese to english, but if you mean that how to custom refresh header or load-more footer, there is an example in folder **example -> App.js**, pass element to prop **_renderHeaderRefresh_**, and params **_gestureStatus_** and **_offset_** will be passed to the element, and then you can custom your message whatever you want.

**Comment by liuyunqiang** [comment]
Load successfully scrollView will scroll to the top scrollComponent = { 'scrollView'}
